/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseMap: typeof import('./src/components/common/BaseMap.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    PaperCard: typeof import('./src/components/papers/PaperCard.vue')['default']
    PaperList: typeof import('./src/components/papers/PaperList.vue')['default']
    PaperMap: typeof import('./src/components/papers/PaperMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parser@7.28.0_axios@1.11.0_embla-carousel@8.6.0_typescript@5.9.2__62f04c26e7dd362328bb5a0122a712f4/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parser@7.28.0_axios@1.11.0_embla-carousel@8.6.0_typescript@5.9.2__62f04c26e7dd362328bb5a0122a712f4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parser@7.28.0_axios@1.11.0_embla-carousel@8.6.0_typescript@5.9.2__62f04c26e7dd362328bb5a0122a712f4/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parser@7.28.0_axios@1.11.0_embla-carousel@8.6.0_typescript@5.9.2__62f04c26e7dd362328bb5a0122a712f4/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parser@7.28.0_axios@1.11.0_embla-carousel@8.6.0_typescript@5.9.2__62f04c26e7dd362328bb5a0122a712f4/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parser@7.28.0_axios@1.11.0_embla-carousel@8.6.0_typescript@5.9.2__62f04c26e7dd362328bb5a0122a712f4/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    ULink: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.0_@babel+parser@7.28.0_axios@1.11.0_embla-carousel@8.6.0_typescript@5.9.2__62f04c26e7dd362328bb5a0122a712f4/node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
  }
}
