words = [
    "augroup",
    "autocmd",
    "basedpyright",
    "bufnr",
    "cclose",
    "commentstring",
    "completeopt",
    "cterm",
    "dapui",
    "ecolog",
    "exafunction",
    "fzf",
    "guifont",
    "hrsh",
    "jsonls",
    "keymaps",
    "linespace",
    "menuone",
    "michhernand",
    "mikavilpas",
    "neovide",
    "noinsert",
    "noselect",
    "omnifunc",
    "onsails",
    "pyproject",
    "rafamadriz",
    "rcarriga",
    "relativenumber",
    "saghen",
    "supermaven",
    "tbl",
    "texlab",
    "vlty",
    "zbirenbaum",
]
