"""fix: REVERSE set Mapped on collection reference

Revision ID: 00f24d2acc42
Revises: eb47e9f6152c
Create Date: 2025-11-10 16:26:56.750687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '00f24d2acc42'
down_revision = 'eb47e9f6152c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
