"""ItemUpdate model fixed plus attachment more

Revision ID: 158446531954
Revises: 6c06cc0e3f1e
Create Date: 2025-08-07 15:39:40.336165

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '158446531954'
down_revision = '6c06cc0e3f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
