"""feat: add timestamps created_at and updated_at to StudySite

Revision ID: 1c6df94c3d7d
Revises: c031ba4c6a18
Create Date: 2025-11-10 14:54:40.594230

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c6df94c3d7d'
down_revision = 'c031ba4c6a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
