"""Move relationships to ItemBase

Revision ID: 1e5741a3fda5
Revises: 40b3bdfca28e
Create Date: 2025-07-31 22:37:59.266656

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1e5741a3fda5'
down_revision = '40b3bdfca28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
