"""feat: Item one-to-many StudySite - drop StudySite owner

Revision ID: 21d6b69f6935
Revises: 41903b127a2c
Create Date: 2025-09-30 14:47:00.574773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21d6b69f6935'
down_revision = '41903b127a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collection_owner_id_fkey'), 'collection', type_='foreignkey')
    op.create_foreign_key(None, 'collection', 'user', ['owner_id'], ['id'])
    op.drop_constraint(op.f('item_study_site_id_key'), 'item', type_='unique')
    op.drop_constraint(op.f('item_study_site_id_fkey'), 'item', type_='foreignkey')
    op.drop_column('item', 'study_site_id')
    op.add_column('studysite', sa.Column('item_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_studysite_item_id'), 'studysite', ['item_id'], unique=False)
    op.drop_constraint(op.f('studysite_owner_id_fkey'), 'studysite', type_='foreignkey')
    op.create_foreign_key(None, 'studysite', 'item', ['item_id'], ['id'])
    op.drop_column('studysite', 'owner_id')
    op.alter_column('tag', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('tag_owner_id_fkey'), 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key(op.f('tag_owner_id_fkey'), 'tag', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tag', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('studysite', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'studysite', type_='foreignkey')
    op.create_foreign_key(op.f('studysite_owner_id_fkey'), 'studysite', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_studysite_item_id'), table_name='studysite')
    op.drop_column('studysite', 'item_id')
    op.add_column('item', sa.Column('study_site_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('item_study_site_id_fkey'), 'item', 'studysite', ['study_site_id'], ['id'])
    op.create_unique_constraint(op.f('item_study_site_id_key'), 'item', ['study_site_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.create_foreign_key(op.f('collection_owner_id_fkey'), 'collection', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
