"""ItemUpdate model fixed plus attachment

Revision ID: 2ff8c4ae9b03
Revises: c5cc7425d89d
Create Date: 2025-08-07 14:47:19.837525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2ff8c4ae9b03'
down_revision = 'c5cc7425d89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
