"""ItemUpdate model fixed plus attachment more3

Revision ID: 38a988624128
Revises: b4df1114854e
Create Date: 2025-08-07 15:13:47.912652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '38a988624128'
down_revision = 'b4df1114854e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('attachment', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'attachment')
    # ### end Alembic commands ###
