"""Fix optionality and defaults of some columns

Revision ID: 3f3ce9470d6b
Revises: 9ea76974bf6a
Create Date: 2025-07-31 18:49:46.771693

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3f3ce9470d6b'
down_revision = '9ea76974bf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'language',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('item', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('item', 'libraryCatalog',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('item', 'rights',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'rights',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('item', 'libraryCatalog',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('item', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('item', 'language',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
