"""Change abstract length

Revision ID: 40b3bdfca28e
Revises: 8d2b789202d3
Create Date: 2025-07-31 19:34:04.744854

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '40b3bdfca28e'
down_revision = '8d2b789202d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'abstractNote',
               existing_type=sa.VARCHAR(length=4096),
               type_=sqlmodel.sql.sqltypes.AutoString(length=8192),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'abstractNote',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=8192),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###
