"""fix: Creators cascading delete fix and loosen some filed restrictions

Revision ID: 477de09adba8
Revises: 73e0546bb93a
Create Date: 2025-11-13 13:19:30.401641

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '477de09adba8'
down_revision = '73e0546bb93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creator', 'firstName',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creator', 'firstName',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
