"""Fix optionality and defaults of date column

Revision ID: 4ab975846099
Revises: 93f886825fcb
Create Date: 2025-07-31 18:55:16.726254

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4ab975846099'
down_revision = '93f886825fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
