"""ItemUpdate model fixed plus attachment more3

Revision ID: 5f342b95bfff
Revises: a8eda1bd5b2f
Create Date: 2025-08-07 15:34:50.593614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f342b95bfff'
down_revision = 'a8eda1bd5b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
