"""fix: set Mapped on collection reference

Revision ID: 668fa8d68d41
Revises: 1c6df94c3d7d
Create Date: 2025-11-10 16:20:17.490730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '668fa8d68d41'
down_revision = '1c6df94c3d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
