"""ItemUpdate model fixed plus attachment more3

Revision ID: 6be10c6dc765
Revises: 38a988624128
Create Date: 2025-08-07 15:21:14.693659

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6be10c6dc765'
down_revision = '38a988624128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
