"""Update datetime handling for Items

Revision ID: 6d294d7ec742
Revises: af33e6b33c83
Create Date: 2025-08-07 15:55:17.075545

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d294d7ec742'
down_revision = 'af33e6b33c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
