"""fix: split StudySite and Location

Revision ID: 7e7fb2e498c2
Revises: 21d6b69f6935
Create Date: 2025-09-30 22:22:35.297203

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e7fb2e498c2'
down_revision = '21d6b69f6935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('studysite', sa.Column('location_id', sa.Uuid(), nullable=False))
    op.alter_column('studysite', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.create_index(op.f('ix_studysite_location_id'), 'studysite', ['location_id'], unique=False)
    op.create_foreign_key(None, 'studysite', 'location', ['location_id'], ['id'])
    op.drop_column('studysite', 'latitude')
    op.drop_column('studysite', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studysite', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('studysite', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'studysite', type_='foreignkey')
    op.drop_index(op.f('ix_studysite_location_id'), table_name='studysite')
    op.alter_column('studysite', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('studysite', 'location_id')
    op.drop_table('location')
    # ### end Alembic commands ###
