"""Fix optionality and defaults of accessDate column

Revision ID: 8676cba409d5
Revises: f5d172af607a
Create Date: 2025-07-31 18:58:35.464631

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8676cba409d5'
down_revision = 'f5d172af607a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
