"""Add helper models for helper tables

Revision ID: 9132f9260870
Revises: cd7f00fcaf8f
Create Date: 2025-07-31 23:35:59.891429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9132f9260870'
down_revision = 'cd7f00fcaf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
