"""fix: add server defaults to timestamp columns

Revision ID: 935fdf0c43c9
Revises: c61a8575c36b
Create Date: 2025-11-10 13:55:33.111107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '935fdf0c43c9'
down_revision = 'c61a8575c36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_location_cluster_label'), table_name='location')
    op.drop_column('location', 'cluster_label')
    op.alter_column('tag', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tag', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('location', sa.Column('cluster_label', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_location_cluster_label'), 'location', ['cluster_label'], unique=False)
    op.alter_column('location', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
