"""Fix optionality and defaults of some columns

Revision ID: 93f886825fcb
Revises: f03f709f68b5
Create Date: 2025-07-31 18:54:11.452107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93f886825fcb'
down_revision = 'f03f709f68b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'abstractNote',
               existing_type=sa.VARCHAR(length=2048),
               type_=sqlmodel.sql.sqltypes.AutoString(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'abstractNote',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=4096),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###
