"""feat: add is_manual flag to study_site

Revision ID: 9a2729365f82
Revises: 00f24d2acc42
Create Date: 2025-11-10 18:16:59.575976

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9a2729365f82'
down_revision = '00f24d2acc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_manual column with server default of False for existing rows
    op.add_column('studysite', sa.Column('is_manual', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_studysite_is_manual'), 'studysite', ['is_manual'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studysite_is_manual'), table_name='studysite')
    op.drop_column('studysite', 'is_manual')
    # ### end Alembic commands ###
