"""ItemUpdate model fixed plus attachment more3

Revision ID: a8eda1bd5b2f
Revises: 6be10c6dc765
Create Date: 2025-08-07 15:23:46.859543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a8eda1bd5b2f'
down_revision = '6be10c6dc765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
