"""Add Zotero tables and columns

Revision ID: ab20fceea8f0
Revises: 1a31ce608336
Create Date: 2025-07-31 18:28:48.678859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ab20fceea8f0'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creatorType', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('firstName', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('itemType', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.add_column('item', sa.Column('abstractNote', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False))
    op.add_column('item', sa.Column('publicationTitle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('volume', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('item', sa.Column('issue', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('item', sa.Column('pages', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('item', sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    op.add_column('item', sa.Column('series', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.add_column('item', sa.Column('seriesTitle', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.add_column('item', sa.Column('seriesText', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('journalAbbreviation', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.add_column('item', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False))
    op.add_column('item', sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.add_column('item', sa.Column('issn', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('item', sa.Column('shortTitle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False))
    op.add_column('item', sa.Column('archive', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.add_column('item', sa.Column('archiveLocation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('libraryCatalog', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('callNumber', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.add_column('item', sa.Column('rights', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('dateAdded', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('item', sa.Column('dateModified', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('item', sa.Column('accessDate', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('item', sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False))
    op.create_index(op.f('ix_item_key'), 'item', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_key'), table_name='item')
    op.drop_column('item', 'key')
    op.drop_column('item', 'accessDate')
    op.drop_column('item', 'dateModified')
    op.drop_column('item', 'dateAdded')
    op.drop_column('item', 'extra')
    op.drop_column('item', 'rights')
    op.drop_column('item', 'callNumber')
    op.drop_column('item', 'libraryCatalog')
    op.drop_column('item', 'archiveLocation')
    op.drop_column('item', 'archive')
    op.drop_column('item', 'url')
    op.drop_column('item', 'shortTitle')
    op.drop_column('item', 'issn')
    op.drop_column('item', 'doi')
    op.drop_column('item', 'language')
    op.drop_column('item', 'journalAbbreviation')
    op.drop_column('item', 'seriesText')
    op.drop_column('item', 'seriesTitle')
    op.drop_column('item', 'series')
    op.drop_column('item', 'date')
    op.drop_column('item', 'pages')
    op.drop_column('item', 'issue')
    op.drop_column('item', 'volume')
    op.drop_column('item', 'publicationTitle')
    op.drop_column('item', 'abstractNote')
    op.drop_column('item', 'itemType')
    op.drop_column('item', 'version')
    op.drop_table('tag')
    op.drop_table('relation')
    op.drop_table('creator')
    op.drop_table('collection')
    # ### end Alembic commands ###
