"""ItemUpdate model fixed plus attachment more2

Revision ID: b4df1114854e
Revises: f2814ce488c0
Create Date: 2025-08-07 15:08:33.650972

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4df1114854e'
down_revision = 'f2814ce488c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
