"""fix: set ClusterCoordinate default name to unknown

Revision ID: c031ba4c6a18
Revises: 72d7480a401f
Create Date: 2025-11-10 14:21:12.496556

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c031ba4c6a18'
down_revision = '72d7480a401f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_cluster_label'), table_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_location_cluster_label'), 'location', ['cluster_label'], unique=False)
    # ### end Alembic commands ###
