"""ItemUpdate model fixed plus attachment

Revision ID: c5cc7425d89d
Revises: bd36ce023756
Create Date: 2025-08-07 14:42:10.100678

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5cc7425d89d'
down_revision = 'bd36ce023756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
