"""Fix optionality and defaults for some columns

Revision ID: ca52ed9d89c2
Revises: ef6303cfa987
Create Date: 2025-07-31 18:41:29.620368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca52ed9d89c2'
down_revision = 'ef6303cfa987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'volume',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('item', 'issue',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('item', 'pages',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('item', 'journalAbbreviation',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('item', 'issn',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'issn',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('item', 'journalAbbreviation',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('item', 'pages',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('item', 'issue',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('item', 'volume',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
