"""Add helper models for helper tables

Revision ID: cd7f00fcaf8f
Revises: 1e5741a3fda5
Create Date: 2025-07-31 23:33:06.262001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd7f00fcaf8f'
down_revision = '1e5741a3fda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'collection', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('relation', 'value')
    op.drop_column('relation', 'key')
    op.add_column('tag', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tag', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'owner_id')
    op.add_column('relation', sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('relation', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'owner_id')
    # ### end Alembic commands ###
