"""fix: REVERSE set Mapped on collection reference

Revision ID: eb47e9f6152c
Revises: 668fa8d68d41
Create Date: 2025-11-10 16:23:15.712476

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb47e9f6152c'
down_revision = '668fa8d68d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
