"""Add Zotero tables and columns

Revision ID: ef6303cfa987
Revises: ab2f9223b222
Create Date: 2025-07-31 18:34:30.988477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ef6303cfa987'
down_revision = 'ab2f9223b222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
