"""Fix optionality and defaults of some columns

Revision ID: f03f709f68b5
Revises: 3f3ce9470d6b
Create Date: 2025-07-31 18:53:17.175231

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f03f709f68b5'
down_revision = '3f3ce9470d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
