"""ItemUpdate model fixed plus attachment more

Revision ID: f2814ce488c0
Revises: 2ff8c4ae9b03
Create Date: 2025-08-07 14:54:21.013239

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f2814ce488c0'
down_revision = '2ff8c4ae9b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'dateAdded',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('item', 'dateModified',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(),
               postgresql_using='"dateModified"::timestamp without time zone',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'dateModified',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('item', 'dateAdded',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
