"""Fix optionality and defaults of accessDate column

Revision ID: f5d172af607a
Revises: 4ab975846099
Create Date: 2025-07-31 18:57:05.692512

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f5d172af607a'
down_revision = '4ab975846099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('item', 'accessDate',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'accessDate',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('item', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
