/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseMap: typeof import('./components/common/BaseMap.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    GraphView: typeof import('./components/GraphView.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    NodeInfoDialog: typeof import('./components/NodeInfoDialog.vue')['default']
    PaperCard: typeof import('./components/papers/PaperCard.vue')['default']
    PaperList: typeof import('./components/papers/PaperList.vue')['default']
    PaperMap: typeof import('./components/papers/PaperMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudySiteCreateDialog: typeof import('./components/maps/StudySiteCreateDialog.vue')['default']
    StudySiteEditDialog: typeof import('./components/maps/StudySiteEditDialog.vue')['default']
    StudySiteMap: typeof import('./components/maps/StudySiteMap.vue')['default']
    TaskProgressBanner: typeof import('./components/common/TaskProgressBanner.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
  }
}
