/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseMap: typeof import('./components/common/BaseMap.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    GraphView: typeof import('./components/GraphView.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    PaperCard: typeof import('./components/papers/PaperCard.vue')['default']
    PaperList: typeof import('./components/papers/PaperList.vue')['default']
    PaperMap: typeof import('./components/papers/PaperMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
  }
}
